[project]
name = "agent-aa-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.35.0,<2.0.0",
    "google-cloud-aiplatform[adk,agent_engines]>=1.135.0",
    "google-cloud-secret-manager>=2.20.0",
    "google-cloud-discoveryengine>=0.13.0",
    "langchain_community",
    "langchain_google_vertexai",
    "langgraph",
    "sqlalchemy-bigquery",
    "google-cloud-bigquery-storage",
    "ipykernel",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
]
